# docker/tasks/main.yml

# # Load environment variables from .env file
# - name: Load environment variables from .env file
#   community.general.env:
#     state: present
#     envfile: "{{ playbook_dir }}/.env"

# Install device-mapper-persistent-data
- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest
  
# Install lvm2
- name: Install lvm2
  yum:
    name: lvm2
    state: latest

# Add Docker repository
- name: Add Docker repository
  command:
    cmd: "sudo yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"

# Install Docker
- name: Install Docker
  yum:
    name: docker-ce
    state: present

# Install python3
- name: Install python3
  yum:
    name: python3
    state: present

# Install Docker Python module
- name: Install Docker Python module
  pip:
    name: docker
    executable: pip3
  vars:
    ansible_python_interpreter: /usr/bin/python3

# Ensure Docker service is running
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
  tags: docker

# Log in to Docker Hub
- name: Log in to Docker Hub
  docker_login:
    username: "{{ lookup('env', 'DOCKER_HUB_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}"
    reauthorize: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
