spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: jdbc:postgresql://${POSTGRE_DB:mypostgresdb}:${POSTGRE_PORT:5432}/{POSTGRE_DB:db}
    username: ${POSTGRE_USER:usr}
    password: ${POSTGRE_PWD:pwd}
    driver-class-name: org.postgresql.Driver
management:
 server:
   add-application-context-header: false
 endpoints:
   web:
     exposure:
       include: health,info,env,metrics,beans,configprops
